export const strings = {
    SELECT: '선택해주세요',
    SERVICE_FUNCTION_ERROR: '서비스의 기능적인 문제',
    LACK_OF_FUNCTION: '원하는 기능이 부족',
    PERSONAL_INFO_LEAK: '개인정보 유출 우려',
    OTHER: '기타 (직접입력)',
    FAREWELL_MESSAGE: '김누구님과 이별인가요?\n너무 아쉬워요.',
    ACCOUNT_DELETION_WARNING: '계정을 삭제하시면 활동 정보 , 잔여 리워드 등은 모두 소멸되며,\n7일간 다시 가입할 수 없어요.',
    LEAVE_REASON_MESSAGE: '피티피티를 떠나시는 이유를 알려주세요.',
    INCONVENIENCE_FEEDBACK_MESSAGE: '불편했던 점을 알려주시면 더 나은 서비스를 위해 노력하겠습니다.',
    NEXT: '다음',
    FINAL_CONFIRMATION_TITLE: '마지막으로 꼭 확인해주세요!',
    WITHDRAW_WARNING_SUBTITLE: '탈퇴 신청 전 꼭 확인해주세요.',
    WITHDRAW_DATA_DELETION_NOTICE: '해당 계정의 활동 정보가 모두 소멸돼요.',
    WITHDRAW_LEGAL_RETENTION_NOTICE: '( 상법 및 전자상거래 등에서의 소비자 보호에 관한 법률 등 관련 법령에서 보존을 요구하는 정보는 해당 법령에서 요구하는 기간 동안 보존합니다. )',
    WITHDRAW_REWARD_DELETION_NOTICE1: '지금까지 획득한 리워드 및 레벨 등은 소멸',
    WITHDRAW_REWARD_DELETION_NOTICE2: '되어 복구할 수 없어요.',
    WITHDRAW_SNS_LINKED_ACCOUNT_NOTICE: '연동된 SNS 계정이 있는 경우 함께 탈퇴돼요.',
    REQUIRED: '(필수)',
    WITHDRAW_AGREEMENT_CONFIRM_TEXT: ' 위 내용을 모두 확인 하였습니다.',
    WITHDRAW: '탈퇴하기',
} as const;
